services:
  backend:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    hostname: mongo
    volumes:
      - ../../data:/data/db
    ports:
      - "27017:27017"