services:
  # Flask backend API service (serves built React app and API)
  backend:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mongodb

  # MongoDB database service for storing recipes and images
  mongodb:
    image: mongo:latest
    hostname: mongo
    volumes:
      - ../../data:/data/db
    ports:
      - "27017:27017"